openapi: 3.0.3
info:
  title: close.io
  description: This is a Close CRM OpenAPI description created by Antilatency
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://api.close.com/api/v1
paths:
  /activity/:
    get:
      tags:
      - activities
      summary: List activities
      operationId: listActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/call/:
    get:
      tags:
      - activities
      summary: List Call activities
      operationId: listCallActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/created/:
    get:
      tags:
      - activities
      summary: List Created activities
      operationId: listCreatedActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/note/:
    get:
      tags:
      - activities
      summary: List Note activities
      operationId: listNoteActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/sms/:
    get:
      tags:
      - activities
      summary: List Sms activities
      operationId: listSmsActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/status_change/lead/:
    get:
      tags:
      - activities
      summary: List LeadStatusChange activities
      operationId: listLeadStatusChangeActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/status_change/opportunity/:
    get:
      tags:
      - activities
      summary: List OpportunityStatusChange activities
      operationId: listOpportunityStatusChangeActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/emailthread/:
    get:
      tags:
      - activities
      summary: List EmailThread activities
      operationId: listEmailThreadActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/email/:
    get:
      tags:
      - activities
      summary: List Email activities
      operationId: listEmailActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/meeting/:
    get:
      tags:
      - activities
      summary: List Meeting activities
      operationId: listMeetingActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/task_completed/:
    get:
      tags:
      - activities
      summary: List TaskCompleted activities
      operationId: listTaskCompletedActivities
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/created/{id}/: 
    get:
      tags:
      - activities
      description: Get Created activity by id
      operationId: getCreatedActivity
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/note/{id}/: 
    get:
      tags:
      - activities
      description: Get Note activity by id
      operationId: getNoteActivity
      security:
      - api_key:
        - write:activity
        - read:activity
    delete:
      tags:
      - activities
      description: Delete Note activity using id
      operationId: deleteNoteActivity
      security:
      - api_key:
        - write:lead
        - read:lead
  /activity/emailthread/{id}/: 
    get:
      tags:
      - activities
      description: Get EmailThread activity by id
      operationId: getEmailThreadActivity
      security:
      - api_key:
        - write:activity
        - read:activity
    delete:
      tags:
      - activities
      description: Delete EmailThread activity using id
      operationId: deleteEmailThreadActivity
      security:
      - api_key:
        - write:lead
        - read:lead
  /activity/email/{id}/: 
    get:
      tags:
      - activities
      description: Get Email activity by id
      operationId: getEmailActivity
      security:
      - api_key:
        - write:activity
        - read:activity
    delete:
      tags:
      - activities
      description: Delete Email activity using id
      operationId: deleteEmailActivity
      security:
      - api_key:
        - write:lead
        - read:lead
  /activity/sms/{id}/: 
    get:
      tags:
      - activities
      description: Get Sms activity by id
      operationId: getSmsActivity
      security:
      - api_key:
        - write:activity
        - read:activity
    delete:
      tags:
      - activities
      description: Delete Sms activity using id
      operationId: deleteSmsActivity
      security:
      - api_key:
        - write:lead
        - read:lead
  /activity/call/{id}/: 
    get:
      tags:
      - activities
      description: Get Call activity by id
      operationId: getCallActivity
      security:
      - api_key:
        - write:activity
        - read:activity
    delete:
      tags:
      - activities
      description: Delete Call activity using id
      operationId: deleteCallActivity
      security:
      - api_key:
        - write:lead
        - read:lead
  /activity/meeting/{id}/: 
    get:
      tags:
      - activities
      description: Get Meeting activity by id
      operationId: getMeetingActivity
      security:
      - api_key:
        - write:activity
        - read:activity
    delete:
      tags:
      - activities
      description: Delete Meeting activity using id
      operationId: deleteMeetingActivity
      security:
      - api_key:
        - write:lead
        - read:lead
  /activity/status_change/lead/{id}/: 
    get:
      tags:
      - activities
      description: Get LeadStatusChange activity by id
      operationId: getLeadStatusChangeActivity
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/status_change/opportunity/{id}/: 
    get:
      tags:
      - activities
      description: Get OpportunityStatusChange activity by id
      operationId: getOpportunityStatusChangeActivity
      security:
      - api_key:
        - write:activity
        - read:activity
  /activity/task_completed/{id}/: 
    get:
      tags:
      - activities
      description: Get TaskCompleted activity by id
      operationId: getTaskCompletedActivity
      security:
      - api_key:
        - write:activity
        - read:activity
    delete:
      tags:
      - activities
      description: Delete TaskCompleted activity using id
      operationId: deleteTaskCompletedActivity
      security:
      - api_key:
        - write:lead
        - read:lead
  /contact/:
    get:
      tags:
      - contacts
      description: List contacts
      operationId: listContacts
      security:
      - api_key:
        - write:lead
        - read:lead
  /contact/{id}/: 
    get:
      tags:
      - contacts
      description: Get contact by id
      operationId: getContact
      security:
      - api_key:
        - write:lead
        - read:lead
    delete:
      tags:
      - contacts
      description: Delete contact using id
      operationId: deleteContact
      security:
      - api_key:
        - write:lead
        - read:lead
  /lead/:
    get:
      tags:
      - leads
      summary: List or search for leads
      operationId: listLeads
      security:
      - api_key:
        - write:lead
        - read:lead
  /lead/merge/:
    post:
      tags:
      - leads
      summary: Merge leads
      operationId: mergeLeads
      security:
      - api_key:
        - write:lead
        - read:lead
  /lead/{id}/:
    get:
      tags:
        - leads
      summary: Get lead by id
      operationId: getLead
      security:
      - api_key:
        - write:lead
        - read:lead
    delete:
      tags:
      - leads
      summary: Delete lead
      operationId: deleteLead
  /opportunity/:
    get:
      tags:
      - opportunities
      summary: List or search for opportunities
      operationId: listOpportunities
      security:
      - api_key:
        - write:lead
        - read:lead

components:
  securitySchemes:
    api_key:
      type: http
      scheme: basic
