openapi: 3.0.3
info:
  title: subville
  description: This is a Subville OpenAPI description created by l-proger (l-proger@yandex.ru)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://subville.com/api/v1
paths:
  /repository/:
    get:
      tags:
      - repository
      summary: List existing repositories
      operationId: listRepositories
      parameters:
      - name: _limit
        in: query
        description: Max repositories in response
        allowEmptyValue: false
        schema:
          type: integer
      - name: _skip
        in: query
        description: Skip first N repositories
        allowEmptyValue: false
        schema:
          type: integer
      responses:
        400:
          $ref: '#/components/responses/RequestIssue'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/OperationNotAllowed'
        405:
          $ref: '#/components/responses/HttpMethodNotSupported'
        415:
          $ref: '#/components/responses/UnsupportedFormat'
        200:         
          description: A list of repositories
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/RepositoryDescriptionArray'
      security:
      - api_key:
        - write:lead
        - read:lead
  /token/:
    post:
      tags:
      - repository
      summary: Login user and return token
      operationId: getToken
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                user_name:          # <!--- form field name
                  type: string
                password:    # <!--- form field name
                  type: string
              required:
                - user_name
                - password
      responses:
        400:
          $ref: '#/components/responses/RequestIssue'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/OperationNotAllowed'
        405:
          $ref: '#/components/responses/HttpMethodNotSupported'
        415:
          $ref: '#/components/responses/UnsupportedFormat'
        200:         
          description: A list of repositories
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/TokenResponse'
      security:
      - api_key:
        - write:lead
        - read:lead
components:
  responses:
    RequestIssue:
      description: Issue with the request
      content: {}
    Unauthorized:
      description: Request needs to be authenticated
      content: {}
    OperationNotAllowed:
      description: Operation not allowed
      content: {}
    HttpMethodNotSupported:
      description: HTTP method not supported
      content: {}
    UnsupportedFormat:
      description: Request used an unsupported format
      content: {}
  schemas:
    TokenResponse:
      type: object
      properties:
        token:
          type: string
        user_name:
          type: string
    RepositoryDescription:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
      
    RepositoryDescriptionArray:
      type: object
      properties:
        has_more:
          type: boolean
        total_results:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/RepositoryDescription'
  securitySchemes:
    api_key:
      type: http
      scheme: basic
